feat: add swc example as a replacement of esbuild
sapphiredev/examples pull request #48
Opened 2022-01-22 19:18 UTC by MajesticString

2022-01-22 19:40 UTC, favna commented
> ESBuild isn't really designed to compile entire folders

Right I should change that to `with-tsup`.. tsup uses esbuild and is much easier to configure and use globby in the background.

2022-01-22 20:54 UTC, MajesticString commented
Should this PR be closed then?

2022-01-22 21:19 UTC, MajesticString commented
Just added a tsup example with this PR

2022-01-23 16:20 UTC, favna requested changes

2022-01-23 16:20 UTC, favna commented on examples/with-tsup/tsup.config.ts
> +	outDir: 'dist'
```suggestion
	clean: true,
	bundle: false,
	dts: false,
	entry: ['src/**/*.ts', '!src/**/*.d.ts'],
	format: ['cjs'],
	minify: false,
	tsconfig: 'tsconfig.json',
	target: 'es2020',
	splitting: false,
	skipNodeModulesBundle: true,
	sourcemap: true,
	shims: false,
	keepNames: true
```

2022-01-23 16:22 UTC, favna approved these changes

2022-01-23 16:25 UTC, merged