Fixing missing dotenv-cra requirements.
sapphiredev/examples pull request #97
Opened 2022-08-21 14:33 UTC by classy-giraffe

Fixing missing dotenv-cra requirements while generating a new project from scratch using the template with Docker support.

2022-08-21 15:31 UTC, favna requested changes

2022-08-21 15:31 UTC, favna commented on examples/with-docker/src/lib/constants.ts
> +export const RandomLoadingMessage = ['Computing...', 'Thinking...', 'Cooking some food', 'Give me a moment', 'Loading...'];
```suggestion
```

This isn't being used anywhere I think?

2022-08-22 06:18 UTC, classy-giraffe commented
Done.

2022-08-22 07:48 UTC, favna approved these changes

2022-08-22 07:50 UTC, favna requested changes
You have to run `yarn install` in the repository to update the lockfile

2022-08-22 08:47 UTC, favna approved these changes

2022-08-22 08:49 UTC, merged